### ISSUE TITLE
Cannot view documentation

### ISSUE THREAD

**Issue by ma-laforge** [JuliaTelecom/DigitalComm.jl#4]
Since the migration to JuliaTelecom, the old URL is no longer working.

We need to change the link in readme.md to the following:
--> https://juliatelecom.github.io/DigitalComm.jl/dev/index.html

@RGerzaguet: There might be other similar issues in your repositories - but you are probably the best to know where they are.

We also need to update the links in UHDBindings.jl:
--> https://juliatelecom.github.io/UHDBindings.jl/dev/index.html

**Comment by RGerzaguet** [comment]
Thanks @ma-laforge it is fixed now ! :)
