### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by ma-laforge** [JuliaTelecom/DigitalComm.jl#5]
It probably would be a good idea to add a license to this package.

I myself have chosen "MIT" for PhysicalCommunications.jl, but you don't have to go that route.

I understand the potential advantages of going to GPL, but I am not necessarily convinced it will be better in mobilizing people to build good, open-source tools.

Whatever you choose, I think many potential users might like to see a license associated with this code.
(Same thing for UHDBindings.jl)

**Comment by RGerzaguet** [comment]
Thanks for the pointers there
I quite agree with that. When it is tools provided for community, MIT licence seems adapted. 
Thanks again !
